sudo: true
dist: xenial
language: python
python:
  - 2.7
services:
  - docker
install:
  - docker build -t travis-ci-build-stages-demo .
  - docker run -d -it -p 80:8080 --name=travis-ci-build-stages-demo travis-ci-build-stages-demo
before_script:
#  - pip install -r requirements.txt
#  - pip install mock
#  - pip install requests
#  - pip install feedparser
script:
  - docker ps | grep -q travis-ci-build-stages-demo
#  - python tests.py
