sudo: true
dist: xenial
language: python
python:
  - 2.7
services:
  - docker
install:
  - docker build -t travis-ci-build-stages-demo .
  - docker run -d -p 127.0.0.1:80:80 --name travis-ci-build-stages-demo travis-ci-build-stages-demo
before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser
script:
  - docker ps | grep -q blog
  - python tests.py
