sudo: true 
dist: xenial
language: python
python:
  - 2.7
services:
  - docker

env:
global:
- COMMIT=${TRAVIS_COMMIT::8}
- REPO="$DOCKER_USER/travis-ci-build-stages-demo"

before_install:
#  - docker build -t $REPO:$COMMIT .
   -'docker build --help'.
  - docker run -d --name travis-ci-build-stages-demo $REPO:$COMMIT
  
script:
  - docker ps | grep -q travis-ci-build-stages-demo
#  - python tests.py
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
